version: "3.7"

services:
  app:
    image: node:16.17.0-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /src
    volumes:
      - ./:/src
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: phonebook

  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - phonebook-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: phonebook

volumes:
  phonebook-mysql-data:
