version: "3.7"

services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: phonebook

  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - phonebook-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: phonebook

volumes:
  phonebook-mysql-data:
