import type { CreationAttributes, QueryInterface } from "sequelize";
import { CommunicationPhoneNumber } from "../models";

const TABLE_NAME = "communication_phone_number";

const communicationPhoneNumbers: CreationAttributes<CommunicationPhoneNumber>[] =
  [
    {
      value: "72312",
      communicationTypeId: 1,
      locationId: 1,
      subscriberId: 30,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "75581",
      communicationTypeId: 1,
      locationId: 1,
      subscriberId: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "79856",
      communicationTypeId: 1,
      locationId: 2,
      subscriberId: 22,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "71702",
      communicationTypeId: 1,
      locationId: 3,
      subscriberId: 11,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "78744",
      communicationTypeId: 1,
      locationId: 2,
      subscriberId: 29,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "75732",
      communicationTypeId: 1,
      locationId: 4,
      subscriberId: 24,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "73857",
      communicationTypeId: 1,
      locationId: 1,
      subscriberId: 30,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "71023",
      communicationTypeId: 1,
      locationId: 1,
      subscriberId: 24,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "74504",
      communicationTypeId: 1,
      locationId: 1,
      subscriberId: 23,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "72526",
      communicationTypeId: 1,
      locationId: 1,
      subscriberId: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "1878",
      communicationTypeId: 2,
      locationId: 3,
      subscriberId: 17,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "1131",
      communicationTypeId: 2,
      locationId: 2,
      subscriberId: 19,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "1735",
      communicationTypeId: 2,
      locationId: 4,
      subscriberId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "1989",
      communicationTypeId: 2,
      locationId: 2,
      subscriberId: 13,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "1311",
      communicationTypeId: 2,
      locationId: 3,
      subscriberId: 11,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "1594",
      communicationTypeId: 2,
      locationId: 2,
      subscriberId: 17,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "1113",
      communicationTypeId: 2,
      locationId: 2,
      subscriberId: 23,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "1254",
      communicationTypeId: 2,
      locationId: 4,
      subscriberId: 16,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "1712",
      communicationTypeId: 2,
      locationId: 2,
      subscriberId: 23,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "1170",
      communicationTypeId: 2,
      locationId: 1,
      subscriberId: 22,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "175",
      communicationTypeId: 3,
      locationId: 3,
      subscriberId: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "152",
      communicationTypeId: 3,
      locationId: 2,
      subscriberId: 19,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "190",
      communicationTypeId: 3,
      locationId: 2,
      subscriberId: 22,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "197",
      communicationTypeId: 3,
      locationId: 4,
      subscriberId: 20,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "3440750",
      communicationTypeId: 4,
      locationId: 1,
      subscriberId: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "2813167",
      communicationTypeId: 4,
      locationId: 1,
      subscriberId: 6,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "6523255",
      communicationTypeId: 4,
      locationId: 3,
      subscriberId: 23,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "8281969",
      communicationTypeId: 4,
      locationId: 1,
      subscriberId: 19,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      value: "3595936",
      communicationTypeId: 4,
      locationId: 4,
      subscriberId: 29,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

module.exports = {
  up: () => {
    return CommunicationPhoneNumber.bulkCreate(communicationPhoneNumbers);
  },
  down: (queryInterface: QueryInterface) => {
    return queryInterface.bulkDelete(
      TABLE_NAME,
      [{ lastname: [communicationPhoneNumbers.map(({ value }) => value)] }],
      {}
    );
  },
};
