import type { CreationAttributes, QueryInterface } from "sequelize";
import { Subscriber } from "../models";

const TABLE_NAME = "subscriber";

const subscribers: CreationAttributes<Subscriber>[] = [
  {
    firstName: "James",
    middleName: "Alan",
    lastName: "Hetfield",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Kirk",
    middleName: "Lee",
    lastName: "Hammet",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Jason",
    middleName: "Curtis",
    lastName: "Newstad",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Lars",
    middleName: "Von",
    lastName: "Ulrich",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Sherry",
    middleName: "Hodges",
    lastName: "Irwin",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Ann",
    middleName: "Katherine",
    lastName: "Rutledge",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Wynn",
    middleName: "White",
    lastName: "Mcfadden",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Sherrie",
    middleName: "Alyce",
    lastName: "May",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Randolph",
    middleName: "Lynch",
    lastName: "Salas",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Amanda",
    middleName: "Ellison",
    lastName: "Spears",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Maritza",
    middleName: "Green",
    lastName: "Francis",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Latisha",
    middleName: "Fleming",
    lastName: "Carrillo",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Maureen",
    middleName: "Durham",
    lastName: "Ratliff",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Mccarthy",
    middleName: "Byers",
    lastName: "Young",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Robbie",
    middleName: "Justice",
    lastName: "Herring",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Bryant",
    middleName: "Hansen",
    lastName: "Chandler",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Mccall",
    middleName: "Jarvis",
    lastName: "Mcleod",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Janell",
    middleName: "Susan",
    lastName: "Serrano",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Mathis",
    middleName: "Tyson",
    lastName: "Watkins",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Ava",
    middleName: "Wilkins",
    lastName: "Collins",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Patel",
    middleName: "Stanton",
    lastName: "Thornton",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Bettye",
    middleName: "Bartlett",
    lastName: "Merrill",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Stout",
    middleName: "Carissa",
    lastName: "Randolph",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Burton",
    middleName: "Erin",
    lastName: "Whitney",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Wendi",
    middleName: "Arlene",
    lastName: "Hunter",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Celeste",
    middleName: "Bonnie",
    lastName: "Hahn",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Terry",
    middleName: "Phelps",
    lastName: "Peck",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Gwendolyn",
    middleName: "Hewitt",
    lastName: "Head",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Gibson",
    middleName: "Trudy",
    lastName: "Sampson",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Willa",
    middleName: "Harding",
    lastName: "Finley",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Freda",
    middleName: "Heath",
    lastName: "Goodman",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Alma",
    middleName: "Gilliam",
    lastName: "Thompson",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Brown",
    middleName: "Floyd",
    lastName: "Welch",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Christian",
    middleName: "Ila",
    lastName: "Daniels",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

module.exports = {
  up: () => {
    return Subscriber.bulkCreate(subscribers);
  },
  down: (queryInterface: QueryInterface) => {
    return queryInterface.bulkDelete(
      TABLE_NAME,
      [{ lastname: [subscribers.map(({ lastName }) => lastName)] }],
      {}
    );
  },
};
