type CommunicationPhoneNumber {
  id: Int!
  value: String!
  communicationTypeId: Int!
  locationId: Int
  subscriberId: Int
}

input communication_phone_numbers_order_by {
  id: OrderBy
  value: OrderBy
  communicationTypeId: OrderBy
  locationId: OrderBy
  subscriberId: OrderBy
}

input communication_phone_numbers_where_exp {
  id: FilterId
  value: FilterString
  communicationTypeId: FilterInt
  locationId: FilterInt
  subscriberId: FilterInt
}
