type Human {
  id: Int!
  firstName: String!
  middleName: String!
  lastName: String!
  subscriber: Subscriber
}

input humans_where_exp {
  id: FilterId
  firstName: FilterString
  lastName: FilterString
  middleName: FilterString
  locations: FilterLocations
  q: FilterString
}

input id {
  id: Int
}

input FilterLocations {
  _eq: id
}
