type Location {
  id: Int!
  country: String!
  region: String
  district: String
  city: String
  street: String
  building: String
  section: String
  floor: String
  room: String
}

input locations_order_by {
  id: OrderBy
  country: OrderBy
  region: OrderBy
  district: OrderBy
  city: OrderBy
  street: OrderBy
  building: OrderBy
  section: OrderBy
  floor: OrderBy
  room: OrderBy
}

input locations_where_exp {
  id: FilterId
  country: FilterString
  region: FilterString
  district: FilterString
  city: FilterString
  street: FilterString
  building: FilterString
  section: FilterString
  floor: FilterString
  room: FilterString
}
