type Query {
  login(email: String!, password: String!): AuthData
  subscribers(limit: Int, offset: Int, order_by: [subscribers_order_by!]): [Subscriber!]!
  subscribers_aggregate: Aggregate!
  subscribers_by_pk(id: Int!): Subscriber
}
