type Subscriber {
  id: Int!
  firstName: String!
  middleName: String!
  lastName: String!
}

input subscribers_where_exp {
  id: FilterId
  firstName: FilterString
  lastName: FilterString
  middleName: FilterString
  q: FilterString
}
