type Subscriber {
  id: Int!
  human: Human
  position: String
  description: String
  locations: [Location!]
}

input subscribers_where_exp {
  id: FilterId
  locations: FilterSubscriberLocations
  q: FilterString
}

input FilterSubscriberLocations {
  _in: [Int!]
}
